### ISSUE TITLE
Positioning STL based on lidar data

### ISSUE THREAD

**Issue by kruusamae** [UTNuclearRoboticsPublic/temoto_intuitive_teleoperator#1]
@shaun-edwards
In order to make the demo more safe and reliable on our mobile platform, we need a way to make real-life objects part of MoveIt! collision scene.
Say we limit the possible real-life objects to 2: one has a round base (a barrel) and the other has a rectangular base (a more complex shape described in an STL-file but the base will be rectangle). Would it be realistic to have something that reads lidar data and positions the object from an STL-file into collision scene to where lidar detected a corner and/or a straight line?

**Comment by shaun-edwards** [comment]
I'm not aware of anything that does this.  A 3D sensor can be used to build a collision map for "unknown" objects.  Alternatively, you could define URDF obstacles that limit the workspace of the arm (in other words, keep-out zones).

**Comment by kruusamae** [comment]
I was thinkng along the lines of using lidar to detect in part the edges (distance from robot's base_link) of rectangular base and then placing a known object to collision scene at the same distance from base_link. Getting the orientation right could possibly be tricky but that's where corners might be helpful. But right now I don't know how much effort would it be to extract the lines and a corner from lidar data.
